# Generated by Django 5.0 on 2024-01-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_post_comments_comment_postcommented_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likers',
        ),
        migrations.AddField(
            model_name='post',
            name='isLiekd',
            field=models.BooleanField(default=False),
        ),
    ]
